format = "$os$username$directory$git_branch$package$rust $cmd_duration\n$character"
add_newline = false

[package]
format = " is [ðŸ“¦ $version]($style)"

[rust]
format = " via [ðŸ¦€ $version]($style)"

[git_branch]
format = " on [î‚  $branch]($style)"

[username]
format = " [$user](bold yellow)"
show_always = true

[character]
success_symbol = " [ó±ž©](bold green)"
error_symbol = " [ó±ž©](bold red)"

[directory]
format = " [$path]($style)"

[os]
disabled = false
format = "$symbol"

symbols.Ubuntu = "[î½²](bold gray)"
symbols.Arch = "[ó°£‡](bold gray)"
symbols.NixOS = "[ïŒ“](bold)"
